version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
